CREATE TABLE registro (ID INT (11) NOT NULL AUTO_INCREMENT, DNI INT (8) NOT NULL, Nombre
VARCHAR (50), Apellido VARCHAR(50), Correo VARCHAR (50), Lugar VARCHAR(50), KEY(ID));
CREATE TABLE visita (ID INT (11) NOT NULL AUTO_INCREMENT, DNI INT (8) NOT NULL, Nombre VARCHAR (50), Apellido VARCHAR (50),
Razon VARCHAR (100), Correo VARCHAR (50), Fecha_entrada VARCHAR (100), Fecha_salida VARCHAR (100) NULL, KEY(ID));
